---
title: "Validate and clean data"
format:
  email:
    table-of-contents: true
    anchor-sections: true
    code-fold: true
    code-overflow: wrap
    code-summary: "Show Code"
    code-tools: true
    code-link: true
editor_options: 
  chunk_output_type: console
---

## Create a summary of records

```{r}
#| label: summarize data
#| eval: !expr 'stop_notice != TRUE'


summary_table <- modeldata_validated |> filter(route_id %in% c(1:5)) |>
  select(route, vessel,date, delay, route_id) |>
  arrange(route_id) |> 
  group_by(route) |>
  mutate(delay = as.numeric(delay), 
         avg_delay = as.numeric(mean(delay)), 
       num_vessels = n_distinct(vessel),
       num_sailings = n()) |>
  ungroup() |> select(-vessel) |> 
  pivot_wider(names_from = date, values_from = delay, values_fn = list) |> 
  gt(rowname_col = "route", groupname_col = "route_id") |>
  tab_header(
    title = "Departure Delays Summary",
    subtitle = glue::glue("{min(modeldata_validated$date)} 
                          to {max(modeldata_validated$date)}")) |>
  tab_source_note(source_note = md("Data sourced from [WSDOT Traveler Information API](https://wsdot.wa.gov/traffic/api/) and modified for use from its original source.")) |> 
  cols_label(
    avg_delay = md("Average delay (min)"),
    num_vessels = "Vessels on route", 
    num_sailings = "Sailings in period"
  ) |> 
  cols_nanoplot(
    columns = starts_with("202"),
    plot_type = "boxplot",
    new_col_name = "nanoplots",
    new_col_label = "delay",
    plot_height = "3em",
    options = nanoplot_options(
      # show_data_points = FALSE
    )) |> 
  fmt_number(columns = avg_delay, decimals = 1) |>
  fmt_number(columns = num_sailings, use_seps = TRUE, decimals = 0) |> 
  opt_all_caps()  |> 
  text_transform(
    locations = cells_stub(),
    fn = function(x) {
      x <- gsub("-", " → ", x)
      x <- gsub("_", " ", x)
      x
    }) |> 
  text_transform(
    locations = cells_group(),
    fn = function(x) " ") |> 
  opt_vertical_padding(scale = 0.2) |> 
  opt_horizontal_padding(scale = 1.5)

summary_table
  

```

```{r}

delays <- modeldata_validated |> select(vessel, date, route, route_id, delay) |> filter(route =="seattle-bainbridge_island") |> filter(year(date) == 2023)

# make a ggplot of delays with months on the x axis and delay on the y. each year a different color.
ggplot(filter(delays,month(date) <4), aes(x = date, y = delay, color = factor(year(date)))) +
  # geom_line() +
  geom_smooth(method = "loess", se = TRUE) +
  labs(title = "Departure Delays by Route",
       x = "Date",
       y = "Delay (min)",
       color = "Year") +
  theme_minimal() 


delays$date |> month()

```

```{r}

ggplot(filter(modeldata_validated, delay < 40)) + geom_histogram(aes(x = delay), bins = 30) + labs(title = "Departure Delays Distribution", x = "Delay (min)", y = "Frequency") + theme_minimal()


```
