---
title: "Read, Explore, and Write Raw Washington State Ferry Data"
output: html_document
format:
  html:
    table-of-contents: true
    anchor-sections: true
    code-fold: true
    code-overflow: wrap
    code-summary: "Show Code"
    code-tools: true
    code-link: true
editor_options: 
  chunk_output_type: console
---

## Retrieve vessel verbose data

```{r}
library(httr2)
library(tidyverse)

base_url <- "https://www.wsdot.wa.gov/Ferries/API/Vessels/rest"

vesselverbose_ep <- "vesselverbose"

req <- request(base_url) |> req_url_query(apiaccesscode = Sys.getenv("WSDOT_ACCESS_CODE"))

vesseldata <- req |> 
  req_url_path_append(vesselverbose_ep) |> 
  req_perform() |> 
  resp_body_string() |> 
  jsonlite::fromJSON() |> 
  as_tibble()

# the results include a nested dataframe of Class information. Unnest this.
vesseldata <- vesseldata |> unnest(Class)

```

## Explore the data
```{r}

str(vesseldata)
summary(vesseldata)



library(skimr)
skim(vesseldata)

library(pointblank)
vessel_scan <- scan_data(vesseldata, sections = "OVMS")
vessel_scan
```



## Retrieve vessel history

```{r}

start_date <- as.character(today() - months(1))
end_date <- as.character(today())
vesselnames <- vesseldata |> pull(VesselName)




get_vesselhistory <- function(vesselname, start_date, end_date) {
  
  cat(glue::glue("Getting vessel history for {vesselname}..."))
  vesselhistory <- request("https://www.wsdot.wa.gov/Ferries/API/Vessels/rest") |> 
    req_url_path_append("vesselhistory", URLencode(vesselname), start_date, end_date) |> 
    req_url_query(apiaccesscode = Sys.getenv("WSDOT_ACCESS_CODE")) |> 
    req_perform() |> 
    resp_body_string() |> 
    jsonlite::fromJSON() |> 
    as_tibble()

  cat(glue::glue("\t{nrow(vesselhistory)} records retrieved for {vesselname}"),"\n")
  vesselhistory
  }


data_list <- map(vesselnames, get_vesselhistory, start_date, end_date)

vesselhistory <- bind_rows(data_list) 


```


##TODO: 
We will want to do an append write on the database to add vesselhistory and could also append weather data?

## Pin data 
For lack of a database for now. 

```{r}
library(pins)

board <- board_connect()

pin_write(board, vesseldata, 
          title="Raw `vesselverbose` data from WSDOT", 
          description="from `Ferries/API/Vessels/rest/vesselverbose`")

pin_write(board, vesselhistory,
          title="Raw `vesselhistory` data from WSDOT",
          description="from `Ferries/API/Vessels/rest/vesselhistory`")

```

