---
title: "Get weather data for terminal locations"
output: html_document
format:
  html:
    table-of-contents: true
    anchor-sections: true
    code-fold: true
    code-overflow: wrap
    code-summary: "Show Code"
    code-tools: true
    code-link: true
editor_options: 
  chunk_output_type: console
---


## Get terminal locations
```{r}

library(httr2)
library(tidyverse)

base_url <- "https://www.wsdot.wa.gov/Ferries/API/terminals/rest"

terminallocations_ep <- "terminallocations"

req <- request(base_url) |> req_url_query(apiaccesscode = Sys.getenv("WSDOT_ACCESS_CODE"))

terminallocations_raw <- req |> 
  req_url_path_append(terminallocations_ep) |> 
  req_perform() |> 
  resp_body_string() |> 
  jsonlite::fromJSON() |> 
  as_tibble()

terminallocations <- terminallocations_raw |> 
  select(TerminalID, TerminalName, Latitude, Longitude)

```


## Get Weather data

```{r}

# note the website says this is equivalent to about 16 API calls in one. Limit is 600 per min, 5k per hour, 10k per day
get_terminal_weather_history <- function(terminal, start_date, end_date) {
  lat <- terminallocations |> filter(TerminalName == terminal) |> pull(Latitude)
  long <- terminallocations |> filter(TerminalName == terminal) |> pull(Longitude)
  
  cat(glue::glue("Getting weather history for {terminal} terminal...\n"))

  
  req <- request("https://archive-api.open-meteo.com/v1/archive") |> 
    req_url_query(latitude=lat, longitude=long,
                  start_date=start_date, end_date=end_date,
                  hourly=c("precipitation","weather_code","cloud_cover_low",
                           "wind_speed_10m","wind_gusts_10m"),
                  temperature_unit="fahrenheit",
                  wind_speed_unit="mph",
                  precipitation_unit="inch", 
                  timezone="America/Los_Angeles",
                  .multi = "comma")
  
  resp <- req |> 
    req_perform() |> 
    resp_body_string() |> 
    jsonlite::fromJSON() |> 
    as_tibble()

  hourly_data <- bind_cols(
    terminal=terminal,
    lat=resp$latitude[1],
    long=resp$longitude[1],
    resp$hourly) 
    
  cat(glue::glue("\t{nrow(hourly_data)} records retrieved for {terminal}"),"\n")

  hourly_data
  }


data_list <- map(terminallocations$TerminalName, get_terminal_weather_history, "2023-05-31", "2024-05-31")

weather_terminal_history_raw <- bind_rows(data_list) 



```


## Pin it

```{r}
library(pins)

board <- board_connect()

pin_write(board, weather_terminal_history_raw,
          type = "csv",
          title = "Raw historical weather data at ferry terminals",
          description = "From `open-meteo.com`, dates 2023-05-31 to 2024-05-31")

```

## Get weather data at time of sailing

```{r}

# uses `weather_terminal_history` and `vesselhistory`
get_sailing_weather <- function(.terminal, .deptime) {
  
  #round to nearest hour
  closest_hour <- round_date(.deptime, "hour")
  
  #look up weather at that time
  result <- weather_terminal_history |> filter(terminal == .terminal & time == closest_hour)
  
  if(nrow(result) == 0){cat(glue::glue("Could not find weather data for {.terminal} on {.deptime}!"))}
  
}


```

